import type { TutorialChapter } from "./catalogTypes.ts";

const playerChapter = (
  slug: string,
  title: string,
  blurb: string,
  seconds: number,
  guide?: string,
): TutorialChapter => ({
  slug,
  title,
  blurb,
  seconds,
  guide,
  visibility: { audiences: ["player"], platforms: ["web", "ios"] },
  mediaKey: `tutorial/player/${slug}.mp4`,
});

const coachChapter = (
  slug: string,
  title: string,
  blurb: string,
  seconds: number,
  platforms: TutorialChapter["visibility"]["platforms"],
  guide?: string,
): TutorialChapter => ({
  slug,
  title,
  blurb,
  seconds,
  guide,
  visibility: { audiences: ["coach"], platforms },
  mediaKey: `tutorial/coach/${slug}.mp4`,
});

export const tutorialChapters: TutorialChapter[] = [
  playerChapter("home", "Start here", "What PongLens does and what Home is showing you.", 34),
  playerChapter(
    "upload",
    "Upload a match",
    "Record or choose a video, then set up the match for processing.",
    39,
    "upload-a-video",
  ),
  playerChapter(
    "viewer",
    "Watch it back",
    "Move point by point, use the player gestures, and open the original upload.",
    55,
    "match-viewer",
  ),
  playerChapter(
    "point",
    "Score a point",
    "Score one rally and add the details that feed analysis and statistics.",
    32,
    "score-points",
  ),
  playerChapter(
    "keepscore",
    "Score Keeper",
    "Score a whole match quickly and correct footage without breaking the flow.",
    60,
    "score-keeper",
  ),
  playerChapter(
    "analysis",
    "Read your match",
    "Read the score, momentum, tactical answers, and placement maps together.",
    43,
    "match-analysis",
  ),
  playerChapter(
    "export",
    "Highlights, export and share",
    "Use automatic highlights, stars, tags, exports, and public links.",
    41,
    "create-share-highlights",
  ),
  playerChapter(
    "coach",
    "You and your coach",
    "Choose match access and receive feedback and lesson entries in context.",
    50,
    "invite-a-coach",
  ),
  playerChapter(
    "journal",
    "The Journal",
    "Keep notes, lessons, scanned pages, current cues, and Recollect together.",
    55,
    "journal",
  ),
  coachChapter(
    "coach-start",
    "Start here",
    "See Coach Home, the roster, and the switch between Playing and Coaching.",
    42,
    ["web", "ios"],
    "coaching-workspace",
  ),
  coachChapter(
    "coach-add-student",
    "Add a student",
    "Start a private lesson record before the student has an account.",
    44,
    ["web", "ios"],
    "add-connect-student",
  ),
  coachChapter(
    "coach-connect-account",
    "Connect their account",
    "Send the invite, apply the student's match access, and merge a duplicate.",
    46,
    ["web", "ios"],
    "add-connect-student",
  ),
  coachChapter(
    "coach-lesson-entry",
    "Write a lesson entry",
    "Capture rough lesson notes and prepare them for later use.",
    48,
    ["web", "ios"],
    "keep-lesson-entries",
  ),
  coachChapter(
    "coach-audio-lesson",
    "Audio record a lesson",
    "Capture the lesson audio and review the transcript and prepared notes.",
    50,
    ["web", "ios"],
    "audio-record-lesson",
  ),
  coachChapter(
    "coach-share-entry",
    "Share it with the student",
    "Send an entry to a connected student's Journal or share that entry by link.",
    43,
    ["web", "ios"],
    "share-coach-entry",
  ),
  coachChapter(
    "coach-review-match",
    "Review their matches",
    "Open shared footage and read the player's score, analysis, and maps.",
    51,
    ["web", "ios"],
    "review-student-match",
  ),
  coachChapter(
    "coach-feedback",
    "Leave feedback",
    "Keep written, spoken, and drawn feedback beside the moment it explains.",
    49,
    ["web", "ios"],
    "leave-match-feedback",
  ),
  coachChapter(
    "coach-paid-review",
    "Paid match reviews",
    "Publish an offering, complete the included review, and deliver it on the web.",
    52,
    ["web"],
    "setup-paid-reviews",
  ),
];
