/**
 * Turn the narration into things machines can read.
 *
 *   node scripts/demos/landing/captions.mjs                 (the landing cut)
 *   node scripts/demos/landing/captions.mjs intro intro    (any other cut)
 *
 * With a name, it writes public/demo/<name>.vtt and stops there. The
 * transcript module below is the landing page's alone: that page embeds the
 * video in indexed HTML and needs the words as text on it, where /videos is
 * noindex and only wants a captions track.
 *
 * The walkthrough's captions are burned into the picture, which is right for
 * a video watched muted and useless for everything else: a screen reader
 * cannot reach them, Google cannot index them, and an answer engine asked
 * "what does PongLens do" has nothing to quote. Every word is already in
 * voice/landing.json with exact timings, so both fall out of it:
 *
 *   public/demo/walkthrough.vtt   a real captions track for the <video>
 *   src/lib/walkthrough.ts        the transcript and duration for the page,
 *                                 its VideoObject markup and its sitemap
 *
 * Generated rather than written by hand for the obvious reason — the script
 * has been rewritten a dozen times, and a transcript that drifts from the
 * narration is worse than none.
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(DIR, "..", "..", "..");
/** Which narration, and what the captions file is called. Defaults to the
 *  landing cut, which is the only one that also gets a transcript module. */
const VOICE = process.argv[2] ?? "landing";
const NAME = process.argv[3] ?? "walkthrough";
const voice = JSON.parse(
  readFileSync(path.join(DIR, "voice", `${VOICE}.json`), "utf8")
);

/**
 * Where the body sits inside the finished file. The composition opens on a
 * logo card before the capture starts (Landing.tsx, INTRO_FRAMES at 30fps),
 * so every line's time in voice/landing.json is that much earlier than the
 * time it is actually heard.
 */
const INTRO_S = 40 / 30;

const stamp = (s) => {
  const t = Math.max(0, s);
  const hh = String(Math.floor(t / 3600)).padStart(2, "0");
  const mm = String(Math.floor((t % 3600) / 60)).padStart(2, "0");
  const ss = String(Math.floor(t % 60)).padStart(2, "0");
  const ms = String(Math.round((t % 1) * 1000)).padStart(3, "0");
  return `${hh}:${mm}:${ss}.${ms}`;
};

const cues = voice.lines.map((l, i) => {
  const from = INTRO_S + l.start;
  return `${i + 1}\n${stamp(from)} --> ${stamp(from + l.dur)}\n${l.text}`;
});
writeFileSync(
  path.join(ROOT, "public", "demo", `${NAME}.vtt`),
  `WEBVTT\n\n${cues.join("\n\n")}\n`
);

if (VOICE !== "landing") {
  console.log(`public/demo/${NAME}.vtt  ${voice.lines.length} cues`);
  process.exit(0);
}

/** Total runtime, and the ISO 8601 form schema.org's `duration` wants. */
const last = voice.lines[voice.lines.length - 1];
const total = Math.round(INTRO_S + last.start + last.dur + 36 / 30);
const mins = Math.floor(total / 60);
const secs = total % 60;

const ts = `/**
 * GENERATED by scripts/demos/landing/captions.mjs — do not edit.
 *
 * The walkthrough's narration as text. It is on the page for three readers
 * at once: a person who would rather skim than watch, a screen reader, and
 * a crawler. The last one is the reason it is real markup and not a file
 * behind a link — a video's words are invisible to search and to answer
 * engines unless they exist as text somewhere on the page that embeds it.
 */

export const WALKTHROUGH = {
  /** Human readable, for the play button. */
  length: ${JSON.stringify(`${mins}:${String(secs).padStart(2, "0")}`)},
  /** ISO 8601, for schema.org VideoObject. */
  duration: ${JSON.stringify(`PT${mins}M${secs}S`)},
  /** Whole seconds. A video sitemap wants a number, not a duration string. */
  durationSeconds: ${total},
  /** The date the current cut was rendered. */
  uploaded: ${JSON.stringify(new Date().toISOString().slice(0, 10))},
  /** Every spoken line, in order. */
  lines: ${JSON.stringify(voice.lines.map((l) => l.text), null, 2)
    .split("\n")
    .join("\n  ")},
} as const;

/** The whole narration as one paragraph, for VideoObject.description. */
export const WALKTHROUGH_TRANSCRIPT = WALKTHROUGH.lines.join(" ");
`;
writeFileSync(path.join(ROOT, "src", "lib", "walkthrough.ts"), ts);

console.log(
  `public/demo/${NAME}.vtt  ${voice.lines.length} cues\n` +
    `src/lib/walkthrough.ts       ${mins}:${String(secs).padStart(2, "0")} (PT${mins}M${secs}S)`
);
