import SwiftUI

/// The ring that turns while a clip is being recut.
///
/// A split, a join or an Adjust changes a point's timing immediately, but
/// the footage behind it is regenerated by the worker a minute later. Until
/// then the chip is showing a clip that no longer matches its own numbers,
/// and without this the whole edit looks like it did nothing at all.
///
/// It owns its own animation deliberately. Driving the rotation from a
/// state variable on the takeover meant one repeating animation shared by
/// every chip on screen, started once in `onAppear` — and anything that
/// interrupted that transaction stopped the spinner everywhere, silently,
/// with the ring frozen at some arbitrary angle that reads as decoration.
struct RecutRing: View {
    var tint: Color = PL.cyan
    var lineWidth: CGFloat = 2.5

    @State private var turning = false

    var body: some View {
        Circle()
            .trim(from: 0, to: 0.3)
            .stroke(tint, style: StrokeStyle(lineWidth: lineWidth, lineCap: .round))
            .rotationEffect(.degrees(turning ? 360 : 0))
            .animation(
                .linear(duration: 0.9).repeatForever(autoreverses: false),
                value: turning
            )
            .onAppear { turning = true }
            .accessibilityHidden(true)
    }
}
