/**
 * Regenerates the effectiveEnd parity fixture.
 *
 *   node --experimental-strip-types scripts/rally-end-fixture.ts
 *
 * The fixture (ios/Tests/fixtures/rally-end-parity.json) carries a table
 * of point shapes and THIS module's answer for each — the web
 * implementation's own output, so the Swift port in Core/Playhead.swift is
 * compared against the original rather than against a second reading of
 * the spec. That is the arrangement that caught the placement mirror; two
 * hand-written suites agreeing only proves both authors read the same
 * sentence the same way.
 *
 * The cases are chosen to cover every branch AND every ranking decision,
 * because the ranking is the part a port gets wrong: which signal wins
 * when both exist, and what a scored point does when tap trimming is off.
 */
import { writeFileSync } from "node:fs";
import { effectiveEnd, paddedEnd, type EndOptions } from "../src/app/match/[id]/playhead.ts";
import type { Point } from "../src/lib/types.ts";

const PAD = { pre: 1.2, post: 1.3 };

/** cut_t0 50, rally 100..104 -> rally end 55.2, padded end 56.5. */
function pt(over: Partial<Point>): Point {
  return {
    id: "p", idx: 1, t0: 100, t1: 104, cut_t0: 50,
    edited: false, tight_start: false, tight_end: false,
    deleted: false, is_let: false,
    scored_at_cut_s: null, rally_end_cut_s: null,
    ...over,
  } as unknown as Point;
}

const OPTIONS: Record<string, EndOptions> = {
  off: { tapEnd: false },
  tapOnly: { tapEnd: true },
  rallyOnly: { tapEnd: false, rallyEnd: { on: true, bufferS: 0.5 } },
  both: { tapEnd: true, rallyEnd: { on: true, bufferS: 0.5 } },
  bothWide: { tapEnd: true, rallyEnd: { on: true, bufferS: 1.5 } },
};

const CASES: { name: string; point: Partial<Point> }[] = [
  { name: "plain", point: {} },
  { name: "tapped", point: { scored_at_cut_s: 54.8 } },
  { name: "tap near the clip end", point: { scored_at_cut_s: 56.4 } },
  { name: "tap before its own clip", point: { scored_at_cut_s: 49.0 } },
  { name: "rally observed", point: { rally_end_cut_s: 53.9 } },
  { name: "rally near the clip end", point: { rally_end_cut_s: 56.4 } },
  { name: "rally before its own clip", point: { rally_end_cut_s: 49.0 } },
  // The point's own end is 55.2. An ending 4.2s before that cannot be what
  // set it, so it is the last bounce the detector managed to see, not the
  // moment the rally stopped.
  { name: "ending does not explain the point's end", point: { rally_end_cut_s: 51.0 } },
  // 2.6s earlier is exactly TAIL_AFTER_BOUNCE: the boundary case, kept.
  { name: "ending explains it, just", point: { rally_end_cut_s: 52.6 } },
  {
    name: "both present, tap later",
    point: { scored_at_cut_s: 54.8, rally_end_cut_s: 53.9 },
  },
  {
    name: "both present, rally later",
    point: { scored_at_cut_s: 52.0, rally_end_cut_s: 55.0 },
  },
  {
    name: "slipped tap with a good rally",
    point: { scored_at_cut_s: 49.0, rally_end_cut_s: 53.9 },
  },
  {
    name: "hand edited with both",
    point: { scored_at_cut_s: 54.8, rally_end_cut_s: 53.9, edited: true },
  },
  { name: "no cut offsets", point: { cut_t0: null, rally_end_cut_s: 53.9 } },
  {
    name: "tight edges",
    point: { rally_end_cut_s: 53.9, tight_start: true, tight_end: true },
  },
];

const rows = CASES.map((c) => {
  const p = pt(c.point);
  return {
    name: c.name,
    point: {
      cut_t0: p.cut_t0, t0: p.t0, t1: p.t1, edited: p.edited,
      tight_start: p.tight_start, tight_end: p.tight_end,
      scored_at_cut_s: p.scored_at_cut_s ?? null,
      rally_end_cut_s: p.rally_end_cut_s ?? null,
    },
    padded_end: paddedEnd(p, PAD),
    ends: Object.fromEntries(
      Object.entries(OPTIONS).map(([k, o]) => [k, effectiveEnd(p, PAD, o)])
    ),
  };
});

const out = {
  note:
    "Generated by scripts/rally-end-fixture.ts from playhead.ts. Core/"
    + "Playhead.swift must reproduce every number. Do not hand-edit.",
  pad: PAD,
  options: OPTIONS,
  cases: rows,
};
const path = "ios/Tests/fixtures/rally-end-parity.json";
writeFileSync(path, `${JSON.stringify(out, null, 2)}\n`);
console.log(`${rows.length} cases x ${Object.keys(OPTIONS).length} settings -> ${path}`);
for (const r of rows) {
  console.log(`  ${r.name.padEnd(28)} padded=${r.padded_end} `
    + Object.entries(r.ends).map(([k, v]) => `${k}=${v}`).join(" "));
}
